services:
  frontend:
    build: ./frontend
    ports:
      - "10200:10200"
    volumes:
      - ./frontend/src:/usr/src/capstone/src
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:10400

  backend:
    build: ./backend
    ports:
      - "10400:10400"
    volumes:
      - ./backend:/backend-server
      - ./local/data:/data
    environment:
      - DATABASE_URI=sqlite+aiosqlite:////data/capstone-database.sqlite