services:
  frontend:
    build: ./frontend
    ports:
      - "10200:10200"
    volumes:
      - ./frontend/src:/usr/src/app/src
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:10400

  backend:
    build: ./backend
    ports:
      - "10400:10400"
    volumes:
      - ./backend:/backend-server

